### ISSUE TITLE
Where is the "source" module?

### ISSUE THREAD

**Issue by paulrigor** [PNNL-m-q/mza#1]
Hi,

I'm trying to understand where the 'source' module is located based on the relative import. Otherwise, what additional setup is required to setup the 'source' model in PYTHONPATH?

Thanks in advance!
https://github.com/PNNL-m-q/mza/blob/807ac92c844428f6d8c710f904d0eba224ce723a/source_code/MzML2mza.py#L4

**Comment by aivett** [comment]
Hi,
Thank you for trying our mza tool! Due to proprietary restrictions from some instrument vendors, the MZA data conversion is a software executable, not open source code. But once the data is converted it is stored as an open format and the examples provided to access it and use it are open source code. If you are interested, I am happy to discuss your use case and see how we can help.
