### ISSUE TITLE
MZA converter export format has diverged from mzapy input format?

### ISSUE THREAD

**Issue by wkumler** [PNNL-m-q/mza#2]
Hi, thanks for developing such an interesting tool! I'm hoping to do some benchmarking of MZA against a SQL database for my own MS data but I'm having trouble using the mzapy package because I'm getting an error when I try to open an .mza file in Python with the `mzapy.MZA` function.

I converted from an mzML file using the v1 download currently available (just redownloaded it to check!) with no extra arguments:

```
> mza -file 180205_Poo_TruePoo_Full1.mzML

Processing file: 180205_Poo_TruePoo_Full1.mzML
    Total time (min): 0.04
```

and while I got a warning (`Not index found and build_index_from_scratch is False`) it seemed to work. However, now when I try to open the file I get:

```
>>> import mzapy
>>> mzapy.MZA("180205_Poo_TruePoo_Full1.mza")

KeyError: "Unable to synchronously open object (object 'Full_mz_array' doesn't exist)"
```

![image](https://github.com/user-attachments/assets/272b2ac7-a6a8-46f9-b24d-e2961a022944)

I used pip to install mzapy just this morning (v.1.7.2) with `pip install mzapy` and that also went off without a hitch. The .mza file itself seems to be fine since [the demo code using h5py](https://github.com/PNNL-m-q/mza/blob/main/examples_Python/Plot_spectrum.py) works just fine but it seems like mzapy is faster / more effective at file access? Is it possible that the package needs to be updated to reflect the new name of the full scan data or is there another way to convert the file to MZA that I'm missing or perhaps a better way to open it?

I'm on Windows 10 with Python 3.12.3.  The file is an Orbitrap MS1 pooled sample that can be downloaded from here: https://github.com/wkumler/mzsql/blob/master/demo_data/180205_Poo_TruePoo_Full1.mzML. It was converted from .raw via msconvert 3.0.22187 with `msconvert 180205_Poo_TruePoo_Full1.raw --filter "peakPicking true 1-" --filter "polarity positive" --noindex`, although the problem doesn't seem to be connected to the lack of an index because I get the same error when I drop the `--noindex` argument (although the warning disappears).

Any advice?

**Comment by aivett** [comment]
Hi wkumler,
Thank you for trying MZA!
The issue is that mzapy is assuming the data was converted to mza from a TOF vendor format (.d) instead of mzML.
When converting from TOF vendor format to mza, the m/z dimension is stored as TOF bins for each spectrum, which are indexes (integers) to the full_mz_array that stores the m/z values.
In this branch @dylanhross made some changes to treat the m/z arrays as m/z values instead of TOF bins https://github.com/PNNL-m-q/mzapy/tree/no_full_mz_array.
Could you please try that mzapy branch and the new version of MZA just released (it should fix issues with index in mzML)?
If the issue with mzapy persists, please open an issue in https://github.com/PNNL-m-q/mzapy/issues
Don't hesitate to ask further questions. I am also interested in the results of your benchmark.
